resolver: lts-22.22
packages:
- foo-bar-api
- foo-bar-api-gen
- foo-bar-api-server
- foo-bar-api-server-gen
- foo-bar-cli
- foo-bar-client

ghc-options:
  "$locals": -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Widentities -Wredundant-constraints -Wcpp-undef

system-ghc: true
nix:
  enable: false
with-hpack: hpack
